#
# Docker Compose configuration
#
# This is used for local development only, not for deployments.
#
# See README.md for usage instructions.
#

version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229 # for attaching Chrome's inspector to a running node process (app or mocha)
    depends_on:
      - db
    links:
      - "db:database"
#    env_file:
#      - ./.env
#    networks:
#      - mock_server

  db:
    build:
      context: .
      dockerfile: PostgresDockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "justfortests"
      POSTGRES_PASSWORD: "rubbish"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgres-data:/var/lib/postgresql/data  
#    networks:
#    - mock_server

#  apollo:
#    image: node 
#    ports:
#    - 6379:6379
#    networks:
#    - mock_server

#networks:
#  mock_server:
#    driver: bridge
